name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: jpenn-dcli/jp-feature
          ref: main
          path: jpenn-dcli/jp-feature/tree/main/kube-manifest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::577638384428:role/EKS_Github_action_iam_role  # IAM role ARN from GitHub secrets
          aws-region: us-east-2  # Explicitly setting AWS region
          role-session-name: GitHubActionsSession  # Session name for the assumed role
          role-duration-seconds: 3600  # Duration of the assumed role session
          audience: sts.amazonaws.com  # Required for OIDC-based authentication

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure kubectl for EKS
        env:
          EKS_CLUSTER_NAME: dcli-sn-eks-cluster
        run: |
          aws eks update-kubeconfig --name "$EKS_CLUSTER_NAME" --region "us-east-2"

      - name: Create namespace
        run: kubectl apply -f kube-manifest/namespace.yaml

      - name: Deploy application
        run: |
          kubectl apply -f kube-manifest/apache-deployment.yaml
          kubectl apply -f kube-manifest/apache-service.yaml
          kubectl apply -f kube-manifest/tomcat-deployment.yaml
          kubectl apply -f kube-manifest/tomcat-service.yaml
          kubectl apply -f kube-manifest/com-demo-alb-ingrss-80.yaml
