name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/ACTIONS_SECRET
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS access key ID from GitHub secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS secret access key from GitHub secrets
          aws-region: ${{ secrets.AWS_REGION }}  # AWS region from GitHub secrets
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}  # IAM role ARN from GitHub secrets
          role-session-name: GitHubActionsSession  # Session name for the assumed role
          role-duration-seconds: 3600  # Duration of the assumed role session
          audience: sts.amazonaws.com  # Required for OIDC-based authentication

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure kubectl for EKS
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Create namespace
        run: kubectl apply -f namespace.yaml

      - name: Deploy application
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f alb-ingress.yaml
